services:
  qcdn:
    image: ghcr.io/arthur2500/qcdn:latest
    container_name: qcdn
    environment:
      DOMAIN: "http://localhost:3000"
      PASSWORDS: "secret123,anotherPassword"
      API_KEYS: "secret123,anotherPassword"
      SESSION_SECRET: "choose_a_strong_secret_here"
      HEAD_TAGS: '<link rel="stylesheet" href="https://cdn.example.com/styles.css">,<script src="https://cdn.example.com/script.js"></script>'
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "3000:3000"